//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESCUELAEntities : DbContext
    {
        public ESCUELAEntities()
            : base("name=ESCUELAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LIBRERIAS> LIBRERIAS { get; set; }
        public virtual DbSet<LIBRO2> LIBRO2 { get; set; }
        public virtual DbSet<USUARIO2> USUARIO2 { get; set; }
    }
}
